| Arguments Keep work_dir: C:\Users\JK\PycharmProjects\2025_AAAI\work_dir/dj30_AAAI_AAAI_adam_mse\2025_AAAI_Exp_None_exp_num_0726/130900
rank:None start_date:['2012-02-02']
Epoch 1, train_loss 1.191701, valid_loss 0
Validation loss decreased (inf --> 1.332834).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 2, train_loss 1.187675, valid_loss 0
Validation loss decreased (1.332834 --> 1.328907).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 3, train_loss 1.194725, valid_loss 0
Validation loss decreased (1.328907 --> 1.325123).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 4, train_loss 1.219041, valid_loss 0
Validation loss decreased (1.325123 --> 1.321460).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 5, train_loss 1.162632, valid_loss 0
Validation loss decreased (1.321460 --> 1.317914).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 6, train_loss 1.169989, valid_loss 0
Validation loss decreased (1.317914 --> 1.314423).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 7, train_loss 1.159102, valid_loss 0
Validation loss decreased (1.314423 --> 1.311038).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 8, train_loss 1.174073, valid_loss 0
Validation loss decreased (1.311038 --> 1.307685).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 9, train_loss 1.157582, valid_loss 0
Validation loss decreased (1.307685 --> 1.304449).  Saving model ...
rank:None start_date:['2012-02-02']
Epoch 10, train_loss 1.125930, valid_loss 0
Validation loss decreased (1.304449 --> 1.301356).  Saving model ...
Successfully loaded best checkpoint...
Test Best Episode
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2021.1.3\plugins\python\helpers\pydev\pydevd.py", line 1551, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2021.1.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\JK\PycharmProjects\2025_AAAI\run.py", line 239, in <module>
    run(cfg)
  File "C:\Users\JK\PycharmProjects\2025_AAAI\run.py", line 186, in run
    trainer.test()
  File "C:\Users\JK\PycharmProjects\2025_AAAI\trainers\AAAI_mse.py", line 318, in test
    ic_mean = np.mean(gathered_ic)
  File "<__array_function__ internals>", line 200, in mean
  File "C:\Users\JK\anaconda3\envs\2025_AAAI_server\lib\site-packages\numpy\core\fromnumeric.py", line 3462, in mean
    return mean(axis=axis, dtype=dtype, out=out, **kwargs)
TypeError: mean() received an invalid combination of arguments - got (axis=NoneType, dtype=NoneType, out=NoneType, ), but expected one of:
 * (*, torch.dtype dtype)
 * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)
 * (tuple of names dim, bool keepdim, *, torch.dtype dtype)